### ISSUE TITLE
Projectiles are broken

### ISSUE THREAD

**Issue by kveex** [MagicalAlexey/Generator-1.21.1#1]
When i try to create an Item that shoots my custom or any standard projectile it just shows an error
Even if i try to make a basic one like an arrow it still doesn't work
![Created files](https://github.com/user-attachments/assets/3271bce8-c7e0-4a3c-8bd0-d05bb07b0d9e)
!{Ranget item properties](https://github.com/user-attachments/assets/43c4cad6-8c7e-4c59-922e-6e4a931a1d15)
![Projectile](https://github.com/user-attachments/assets/3d5924a8-0d8e-443c-ba1a-8ac3f38d741e)
[console.txt](https://github.com/user-attachments/files/16516356/console.txt)

**Comment by MagicalAlexey** [comment]
I know the problem, i'm working on a solution

**Comment by MagicalAlexey** [comment]
Resolved in 1.4
