### ISSUE TITLE
Blocks not dropping things when broken.

### ISSUE THREAD

**Issue by Pupyrinth** [MagicalAlexey/Generator-1.21.1#2]
I honestly don't know if it's cause the plugin/generator or I'm just doing something else wrong. But blocks I create don't drop anything when it's broken. There's nothing in the console about it.
I did try with a different generator and that works as expected, which is why I suspect this, but still not sure.
Please let me know if there's anything else you'd need~

Here's the workspace:
https://cloud.gliroid.com/s/o5ZdwrLzNorHXzr

**Comment by Pupyrinth** [comment]
Oh yeah, I'm using the latest 1.5 release of the generator

**Comment by Pupyrinth** [comment]
Same with the latest 1.6 version, even on a new workspace.

**Comment by MagicalAlexey** [comment]
Okay, I'll test it tomorrow.

**Comment by MagicalAlexey** [comment]
Fiixed in 1.7

**Comment by Pupyrinth** [comment]
Awesome! Thank you 😄
